return {
	a = "com.daymore.Across",
	b = "app.zen-browser.zen",
	c = "dev.zed.Zed-Nightly",
	f = "com.apple.finder",
	g = "com.openai.codex",
	h = "com.anthropic.claudefordesktop",
	j = "com.google.GeminiMacOS",
	k = "com.kakao.KakaoTalkMac",
	l = "ru.keepcoder.Telegram",
	m = "com.apple.mail",
	n = "com.apple.Notes",
	t = "com.github.wez.wezterm",
	v = "com.google.Chrome",
	x = "com.apple.dt.Xcode",
	z = "com.google.android.studio",
}
