return {
	a = "com.daymore.Across",
	b = "app.zen-browser.zen",
	c = "dev.zed.Zed-Nightly",
	d = "com.jetbrains.datagrip",
	f = "com.apple.finder",
	g = "com.openai.codex",
	h = "com.anthropic.claudefordesktop",
	k = "com.kakao.KakaoTalkMac",
	l = "ru.keepcoder.Telegram",
	m = "com.apple.mail",
	n = "notion.id",
	o = "com.microsoft.Outlook",
	s = "com.tinyspeck.slackmacgap",
	t = "com.github.wez.wezterm",
	v = "com.google.Chrome",
}
